name: Build Docker Images on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker images for main
        if: github.ref_type == 'tag' && github.event.ref_type == 'branch' && startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/main'
        run: |
          docker build -t deligianp/uni:latest .
          docker build -t deligianp/uni:${{ env.TAG }} .
          docker push deligianp/uni:latest
          docker push deligianp/uni:${{ env.TAG }}

      - name: Build and push Docker image for migrations
        if: github.ref_type == 'tag' && github.event.ref_type == 'branch' && startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/migrations'
        run: |
          docker build -t deligianp/uni:${{ env.TAG }} .
          docker push deligianp/uni:${{ env.TAG }}
