name: Build Docker Images on Push

on:
  push:
    branches:
      - main
      - migrations

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker images for main
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t deligianp/uni:${{ env.DATE }} .
          docker build -t deligianp/uni:edge .
          docker push deligianp/uni:${{ env.DATE }}
          docker push deligianp/uni:edge

      - name: Build and push Docker image for migrations
        if: github.ref == 'refs/heads/migrations'
        run: |
          docker build -t deligianp/uni:${{ env.DATE }}-synced-migrations .
          docker push deligianp/uni:${{ env.DATE }}-synced-migrations
