name: release
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  makemigrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checking out repository
        with:
          ref: release
      - uses: actions/setup-python@v5
        name: Setting up Python 3.12
        with:
          python-version: 3.12
      - name: Fetch and rebase branch main onto releases
        run: |
          git config --global user.name 'deligianp'
          git config --global user.email 'deligianp@users.noreply.github.com'
          git fetch origin main
          git merge origin/main --no-commit --no-ff
      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Adding merged changes to commit
        run: |
          git add -A
      - name: Making migrations
        run: |
          python manage.py makemigrations --noinput
      - name: Adding potential migration files to commit
        run: |
          git add -f */migrations/*.py
      - name: Conditionally commit changes
        run: |
          git commit -m "Releasing changes for commit #$(git rev-parse --short "$GITHUB_SHA") from main branch

          - Include changes
          - Include potential new migrations"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release