name: release
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  makemigrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checking out repository
        with:
          ref: release
      - uses: actions/setup-python@v5
        name: Setting up Python 3.12
        with:
          python-version: 3.12
      - name: Fetch and rebase branch main onto releases
        run: |
          git config --global user.name 'deligianp'
          git config --global user.email 'deligianp@users.noreply.github.com'
          git fetch origin main
          git merge origin/main --no-commit
      - name: Install Django dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Making migrations
        run: |
          python manage.py makemigrations --noinput
      - name: Adding potential migration files to commit
        run: |
          git add */migrations/*.py
          if [-z git diff --cached --name-only]
            then echo "commit=true" >> $GITHUB_ENV
            else echo "commit=false" >> $GITHUB_ENV
          fi
      - name: Conditionally commit changes
        if: env.commit == 'true'
        run: |
          git commit -m "Update migrations for commit '$(echo "${{ github.event.head_commit.message }}" | cut -c1-32 )'

          Update migrations for commit '${{ github.event.head_commit.message }}'"
      - name: Log commits
        run: |
          git log --graph
